name: Deploy static app to EC2 (push-only app/)

on:
  push:
    branches: ["main"]

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2                 # your region
      EC2_KEY_NAME: simple-web-demo-key     # your EC2 key pair name
      WEB_ROOT: /opt/simple-web-demo/app    # where files live on server
      CONTAINER: simple-web-demo            # nginx container name
      PORT: "8080"                          # public port

    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Only run when app/** changed (or this workflow changed)
      - name: Detect changed paths
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            app:
              - 'app/**'
            workflow:
              - '.github/workflows/deploy.yml'

      - name: Stop early if no app changes
        if: steps.changes.outputs.app != 'true' && steps.changes.outputs.workflow != 'true'
        run: |
          echo "No app/ changes; skipping deploy."
          exit 0

      # AWS needed to discover instance & manage SG temporarily
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Find your running instance created with this key pair
      - name: Find EC2 host & SGs
        id: ec2
        shell: bash
        run: |
          set -euo pipefail
          HOST=$(aws ec2 describe-instances \
            --filters "Name=key-name,Values=${EC2_KEY_NAME}" "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].PublicDnsName" --output text)
          if [[ -z "$HOST" || "$HOST" == "None" ]]; then
            echo "No running instance found with key-name=${EC2_KEY_NAME} in ${AWS_REGION}"
            exit 1
          fi
          SG_IDS=$(aws ec2 describe-instances \
            --filters "Name=key-name,Values=${EC2_KEY_NAME}" "Name=instance-state-name,Values=running" \
            --query "Reservations[].Instances[].SecurityGroups[].GroupId" --output text)
          echo "host=$HOST" >> "$GITHUB_OUTPUT"
          echo "sg_ids=$SG_IDS" >> "$GITHUB_OUTPUT"

      # Allow this GitHub runner to SSH (port 22) temporarily
      - name: Authorize runner IP for SSH (temp)
        id: sshopen
        shell: bash
        run: |
          set -euo pipefail
          RUNNER_IP=$(curl -s https://checkip.amazonaws.com | tr -d '\n')
          echo "Runner IP: $RUNNER_IP"
          for SG in ${{ steps.ec2.outputs.sg_ids }}; do
            aws ec2 authorize-security-group-ingress \
              --group-id "$SG" \
              --ip-permissions "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${RUNNER_IP}/32,Description=gha-temp}]" \
              || true
          done
          echo "runner_ip=$RUNNER_IP" >> "$GITHUB_OUTPUT"

      # Prepare the server once (install docker, create dir, start nginx container with a bind mount)
      - name: One-time prep on server (docker + nginx container)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ steps.ec2.outputs.host }}
          username: ec2-user
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            set -euo pipefail
            WEB_ROOT="${{ env.WEB_ROOT }}"
            CONTAINER="${{ env.CONTAINER }}"
            PORT="${{ env.PORT }}"

            # Install docker if missing
            if ! command -v docker >/dev/null 2>&1; then
              curl -fsSL https://get.docker.com | sh
              sudo systemctl enable --now docker
            fi

            # Ensure target directory exists and is writable by ec2-user
            sudo mkdir -p "${WEB_ROOT}"
            sudo chown -R "$USER:$USER" "$(dirname "${WEB_ROOT}")"

            # If container doesn't exist, create it with a bind mount to WEB_ROOT
            if ! sudo docker ps -a --format '{{.Names}}' | grep -qx "${CONTAINER}"; then
              sudo docker run -d --name "${CONTAINER}" \
                -p ${PORT}:80 \
                -v "${WEB_ROOT}":/usr/share/nginx/html:ro \
                --restart unless-stopped \
                nginx:alpine
            else
              # Ensure it's running
              sudo docker start "${CONTAINER}" >/dev/null 2>&1 || true
            fi

      # Copy only changed app/ files to the server
      - name: Upload app/ to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ steps.ec2.outputs.host }}
          username: ec2-user
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          source: "app/*"
          target: "${{ env.WEB_ROOT }}/"
          overwrite: true
          strip_components: 1

      # Reload nginx so it picks up new files (no container restart required)
      - name: Reload nginx (no-downtime)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ steps.ec2.outputs.host }}
          username: ec2-user
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            set -euo pipefail
            CONTAINER="${{ env.CONTAINER }}"
            # Try graceful reload; fallback to HUP
            sudo docker exec "${CONTAINER}" nginx -s reload || sudo docker kill -s HUP "${CONTAINER}" || true
            # Show what we serve now
            sudo docker exec "${CONTAINER}" sh -c 'ls -la /usr/share/nginx/html | tail -n +1'

      # Clean up SSH ingress rule
      - name: Revoke runner IP for SSH (cleanup)
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          RUNNER_IP="${{ steps.sshop en.outputs.runner_ip }}"
          RUNNER_IP="${RUNNER_IP:-${{ steps.sshopen.outputs.runner_ip }}}"
          if [[ -n "$RUNNER_IP" ]]; then
            for SG in ${{ steps.ec2.outputs.sg_ids }}; do
              aws ec2 revoke-security-group-ingress \
                --group-id "$SG" \
                --ip-permissions "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${RUNNER_IP}/32,Description=gha-temp}]" \
                || true
            done
          fi

      # Quick smoke test
      - name: Smoke test
        env:
          HOST: ${{ steps.ec2.outputs.host }}
          PORT: ${{ env.PORT }}
        run: |
          curl -fsS --max-time 10 "http://${HOST}:${PORT}/?nocache=$(date +%s)" >/dev/null
