name: PR Check (ssg-examples)

on:
  pull_request:
    branches: [ main ]
    paths:
      - "app/**"
      - "Dockerfile"
      - ".github/workflows/pr-check.yml"

permissions:
  contents: read

concurrency:
  group: pr-check-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pr-check:
    name: Build & sanity check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show changed files
        run: |
          git --no-pager diff --name-only \
            "${{ github.event.pull_request.base.sha }}"...${{ github.sha }}

      - name: Basic project sanity (presence of app/index.html)
        run: |
          test -f app/index.html || { echo "ERROR: app/index.html missing"; exit 1; }
          head -n 1 app/index.html || true

      - name: Docker build test (lint-by-build)
        run: |
          docker version
          docker build -t prcheck:test .
